# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=100)),
                ('course_ID', models.CharField(max_length=15)),
                ('course_acronym', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_credits', models.IntegerField(choices=[(2, '2 Credits'), (4, '4 Credits')], default=4, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Offered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronFrame.Course')),
            ],
        ),
    ]
