# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0002_auto_20151209_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(choices=[(2, '2 Credits'), (4, '4 Credits')], default=4),
        ),
    ]
