# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0005_auto_20151209_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSign',
            fields=[
                ('sign', models.CharField(default='WOLOLOLO', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='offered',
            name='end_time',
            field=models.CharField(choices=[('1', '08:00'), ('2', '08:30'), ('3', '09:00'), ('4', '09:30'), ('5', '10:00'), ('6', '10:30'), ('7', '11:00'), ('8', '11:30'), ('9', '12:00'), ('10', '12:30'), ('11', '01:00'), ('12', '01:30'), ('13', '02:00'), ('14', '02:30'), ('15', '03:00'), ('16', '03:30'), ('17', '04:00'), ('18', '04:30'), ('19', '05:00'), ('20', '05:30'), ('21', '06:00'), ('22', '06:30')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='offered',
            name='start_time',
            field=models.CharField(choices=[('1', '08:00'), ('2', '08:30'), ('3', '09:00'), ('4', '09:30'), ('5', '10:00'), ('6', '10:30'), ('7', '11:00'), ('8', '11:30'), ('9', '12:00'), ('10', '12:30'), ('11', '01:00'), ('12', '01:30'), ('13', '02:00'), ('14', '02:30'), ('15', '03:00'), ('16', '03:30'), ('17', '04:00'), ('18', '04:30'), ('19', '05:00'), ('20', '05:30'), ('21', '06:00'), ('22', '06:30')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='offered',
            name='callSign',
            field=models.ForeignKey(default='WOLOLOLO', on_delete=django.db.models.deletion.CASCADE, to='kronFrame.CallSign'),
        ),
    ]
