# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0006_auto_20151215_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsign',
            name='sign',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='offered',
            name='callSign',
        ),
        migrations.AddField(
            model_name='offered',
            name='callSign',
            field=models.ManyToManyField(to='kronFrame.CallSign'),
        ),
    ]
