# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0007_auto_20151215_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='offered',
            name='areaName',
            field=models.CharField(default='WOLOLOLO', max_length=10),
            preserve_default=False,
        ),
    ]
