# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0008_offered_areaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_ID',
            field=models.CharField(max_length=25),
        ),
    ]
