# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0009_auto_20151215_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offered',
            name='areaName',
            field=models.CharField(max_length=50),
        ),
    ]
