# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0010_auto_20151215_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsign',
            name='sign',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
